update_fastlane
opt_out_usage
default_platform(:ios)

platform :ios do
    desc “Generate .ipa file”
    lane :build do
        build_app(
            #skip_profile_detection: true,
            scheme: "BadHabbit",
            silent: true,
            clean: true,
            output_directory: "IpaBuild",
            output_name: "BadHabbit.ipa",
            export_method: "development"
            # Uncomment the line if you want to use Xcode’s Automatically Manage Signing feature
            # xcargs: "-allowProvisioningUpdates"
        )
    end
end
