# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage

default_platform(:ios)

platform :ios do
    desc “Generate .ipa file”
    lane :build do
        build_app(
            scheme: "SettingsTest",
            silent: true,
            clean: true,
            output_directory: "./build",
            output_name: "SettingsTest.ipa",
            export_method: "development"
            # Uncomment the line if you want to use Xcode’s Automatically Manage Signing feature
            # xcargs: "-allowProvisioningUpdates"
        )
    end
end
