source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'

target 'BadHabbit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BadHabbit
  pod 'SwiftGen', '~> 6.0'
  pod 'SnapKit', '~> 5.0.0'

end
